[package]
name = "remainder"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }

[dependencies.rusqlite]
version = "0.32.1"
features = [
	"uuid",
]

[dependencies.uuid]
version = "1.11.0"
features = [
	"v4",
]
